### ISSUE TITLE
Integrate backend for services page 

### ISSUE THREAD

**Issue by mohammedmisbahuddin** [saqlain2301/4thcoordinate#10]
> Refer Index.html for Team and News integration

**Comment by MdUsmanF** [comment]
Integrated backend for services page. getting error while pushing to branch.

**Comment by mohammedmisbahuddin** [comment]
keep commiting changes in local, will push once we can meet...!

**Comment by MdUsmanF** [comment]
The changes mentioned are made. will push to branch when  we  meet.
